version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel
      MYSQL_USER: samrudh
      MYSQL_PASSWORD: 12345@sam
    ports:
      - "3035:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
